site_name: Vehicle Physics Pro
site_description: Documentation for Vehicle Physics Pro (VPP), a realistic vehicle simulation model for Unity 3D
site_author: Angel "Edy" Garcia
repo_url: https://github.com/EdyJ/vehicle-physics-docs

strict: true
google_analytics: [ 'UA-58719504-1', 'auto' ]

theme_dir: 'custom_theme'
theme: cerulean

extra_css: [ 'css/tables.css', 'css/admonitions.css', 'css/fixes.css', 'css/extras.css' ]
extra_javascript: [ 'https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML', 'js/mathjaxhelper.js', 'js/fabric.custom.min.js', 'js/texturecanvas.js' ]

markdown_extensions:
  - extra
  - admonition
  - iconfonts:
      base: "fa"
      prefix: "fa-"
  - mathjax

pages:
- "&#8201;": index.md
- Overview:
  - Features: overview/features.md
  - Licensing: overview/licensing.md
  - Early Access: early-access.md
  - Comparison with other kits: overview/comparison.md
  - Markdown test page: markdown-test.md
- User Guide:
  - Getting started: user-guide/getting-started.md
  - Creating vehicles: user-guide/vehicle-creation.md
  - Vehicle setup guide: user-guide/vehicle-setup.md
  - Requirements for 3D models: user-guide/3d-models.md
- Components:
  - Vehicle Controller: components/vehicle-controller.md
  - Wheel Collider: components/wheel-collider.md
  - Input: components/vehicle-input.md
  - Add-ons: components/vehicle-addons.md
  - Debug: components/vehicle-debug.md
  - Ground materials: components/ground-materials.md
  - Camera: components/camera.md
- Blocks:
  - Steering: blocks/steering.md
  - Brakes: blocks/brakes.md
  - Tires: blocks/tires.md
  - Driveline: blocks/driveline.md
  - Differential: blocks/differential.md
  - Torque Splitter: blocks/torque-splitter.md
  - Engine: blocks/engine.md
  - Clutch: blocks/clutch.md
  - Gearbox: blocks/gearbox.md
  - Retarder: blocks/retarder.md
  - Other blocks: blocks/extra-blocks.md
- Advanced:
  - Creating custom vehicles: advanced/custom-vehicles.md
  - Creating custom blocks: advanced/custom-blocks.md
  - Creating add-on components: advanced/custom-addons.md
  - VehicleBase reference: advanced/vehiclebase-reference.md
  - Data Bus reference: advanced/databus-reference.md
  - Miscelaneous topics explained: advanced/misc-topics-explained.md
  - How suspensions work: advanced/how-suspensions-work.md
  - Configuring realistic vehicles: advanced/configuring-realistic-vehicles.md
  - GIT Repository setup: advanced/git-repository-setup.md

