site_name: Vehicle Physics Pro
theme_dir: 'custom_theme'
theme: cerulean
markdown_extensions: ['extra', 'admonition', 'mathjax', 'iconfonts(base=fa,prefix=fa-)']

extra_css: ['css/tables.css','css/admonitions.css','css/fixes.css','css/extras.css']
extra_javascript: ['https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML','js/mathjaxhelper.js','js/fabric.custom.min.js']

repo_url: https://github.com/EdyJ/vehicle-physics-docs

pages:
- ['index.md', 'Vehicle Physics Pro online documentation']

- ['early-access.md', 'EARLY ACCESS']

- ['user-guide/vehicle-creation.md', 'User Guide', 'Creating a vehicle']
- ['user-guide/visual-effects.md', 'User Guide', 'Adding visual effects']
- ['user-guide/sounds.md', 'User Guide', 'Adding sounds and audio effects']
- ['user-guide/vehicle-interaction.md', 'User Guide', 'Interacting with vehicles']
- ['user-guide/vehicle-setup.md', 'User Guide', 'Configuring and tunning vehicles']
- ['user-guide/3d-models.md', 'User Guide', 'Requirements for 3D models']

- ['markdown-test.md', 'User Guide', 'Markdown test page']

- ['components/vehicle-controller.md', 'Components', 'Vehicle Controller']
- ['components/vehicle-input.md', 'Components', 'Vehicle Input']
- ['components/vehicle-audio.md', 'Components', 'Vehicle Audio']
- ['components/vehicle-telemetry.md', 'Components', 'Vehicle Telemetry']
- ['components/skidmarks-and-smoke.md', 'Components', 'Skidmarks and Smoke']
- ['components/wheel-helper.md', 'Components', 'Wheel Helper']
- ['classes/vehicle-controller-base.md', 'Classes', 'VPVehicleControllerBase']
- ['classes/component.md', 'Classes', 'VPComponent']
- ['classes/solver.md', 'Classes', 'VPSolver']
- ['classes/databus.md', 'Classes', 'VPDataBus']
- ['classes/wheel.md', 'Classes', 'VPCWheel']
- ['classes/engine.md', 'Classes', 'VPCEngine']
- ['classes/gearbox.md', 'Classes', 'VPCGearbox']
- ['classes/differential.md', 'Classes', 'VPCDifferential']
- ['classes/brakes.md', 'Classes', 'VPBrakes']
- ['classes/steering.md', 'Classes', 'VPSteering']
- ['classes/extra-classes.md', 'Classes', 'Other classes']
- ['advanced/custom-components.md', 'Advanced', 'Creating custom components']
- ['advanced/custom-vehicles.md', 'Advanced', 'Creating custom vehicles']
- ['advanced/developing-addons.md', 'Advanced', 'Writting add-on features']
- ['advanced/databus-reference.md', 'Advanced', 'Data Bus reference']
- ['advanced/misc-topics-explained.md', 'Advanced', 'Miscelaneous topics explained']
